import Head from 'next/head';
import React from 'react';
import Footer from '../components/Footer/Footer';
import Header from '../components/Header/Header';

interface Props {
    children: React.ReactNode;
}

const Main = (props : Props) => {
    const { children } = props;
    return (
        <div className="layout">
            <Head>
                <title>Butik Zahrazhafira</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />

            <main className="mt-[70px] mb-8" style={{ 'marginTop': '70px' }}>
                {children}
            </main>
            <footer>
                <Footer />
            </footer>
        </div>
    );
};

export default Main;
